---

- name: restart game servers
  service: name={{ item }} enabled=yes state=restarted
  with_items:
    - bungeecord
    - lobby
    - vanilla
    - survival

- name: stop game servers
  service: name={{ item }} state=stopped
  with_items:
    - bungeecord
    - lobby
    - vanilla
    - survival