---
# Configure virtualhost

- name: Creating virtual host file
  template: src=minecraft-of-by.conf.j2 dest=/etc/apache2/sites-available/{{ site_name }}.conf

- name: Update site path in application.wsgi
  replace: dest="{{ site_path }}/public_html/etc/application.wsgi" regexp="(\/home\/dmitry\/vhosts\/dev\.minecraft\.of\.by)" replace="{{ site_path }}"

- name: Enable Apache2 modules
  apache2_module: name={{ item }} state=present
  with_items:
    - "rewrite"
    - "wsgi"
    - "headers"
    - "expires"

- name: a2ensite {{ site_name }}.conf
  command: a2ensite {{ site_name }}.conf
  args:
    creates: /etc/apache2/sites-enabled/{{ site_name }}.conf
  notify:
    - restart apache2
