---

- name: Install frontend dependencies (npm)
  become: yes
  become_user: "{{ site_user }}"
  become_method: sudo
  npm:
    path: "{{ site_path }}/public_html/mob/static"
    state: present

- name: Build frontend assets with Vite
  become: yes
  become_user: "{{ site_user }}"
  become_method: sudo
  command: npm run build
  args:
    chdir: "{{ site_path }}/public_html/mob/static/"
