---

- name: Create project folder
  file: path="{{site_path}}" state=directory mode=775 owner={{ site_user }} group={{ site_group }}

- name: Create project folders if not exists
  file: path="{{site_path}}/{{ item.name }}" state=directory mode={{ item.mode }} owner={{ item.user }} group={{ item.group }}
  with_items:
    - "{{ site_folders }}"

- name: Checkout site repo
  become: yes
  become_user: "{{ site_user }}"
  become_method: sudo
  git: repo={{ site_repo }} dest={{ site_path }}/public_html force=yes accept_hostkey=yes

- name: Update public_html files owner
  command: find {{ site_path }}/public_html -exec chown {{ site_user }}:www-data {} \;

- name: Ensure files are 0644
  command: find {{ site_path }}/public_html -type f -exec chmod 0644 {} \;

- name: Install specified python requirements in indicated (virtualenv), step 1
  become: yes
  become_user: "{{ site_user }}"
  become_method: sudo
  pip:
    requirements: "{{ site_path }}/public_html/requirements/production.txt"
    virtualenv: "{{ site_path }}/public_html/python-bin"
    virtualenv_command: python3 -m venv

- name: Install dev dependencies, step 2
  become: yes
  become_user: "{{ site_user }}"
  become_method: sudo
  pip:
    requirements: "{{ site_path }}/public_html/requirements/development.txt"
    virtualenv: "{{ site_path }}/public_html/python-bin"
    virtualenv_command: python3 -m venv
  when: env_type is defined and env_type == "dev"
