mode: update
server_env: live
server_version: 1.21.10

minecraft_user: minecraft
minecraft_group: minecraft
server_repo: "git@github.com:DmitryRendov/mob-server.git"

minecraft_home: /home/minecraft
server_folder: "{{ minecraft_home }}/mob-servers"
backup_folder: "{{ minecraft_home }}/backups/worlds"

# Minecraft database configuration
minecraft_db_name: mob_server
minecraft_db_user: minecraft
bucket: mob-server-backups
server_db_src: "{{ server_env }}/{{ server_version }}/latest/survival.dump.tar.gz"

service_restart_cooldown: 10
service_stop_cooldown: 10
