# -*- mode: ruby -*-
# vi: set ft=ruby :

# ** Local envs provisioning **
#
# Server #1 - Ansible node (Debian 8)
# Server #2 - MOB server with predefined 'minecraft' user (Debian 8)
#

# pre-reqs:
#
# ~/.ssh/{id_rsa_mobdeploy.pem, id_rsa_mobdeploy.pub} - deployment key, added to mob-server repo
# ~/.ssh/{id_rsa_mobadmin.pem, id_rsa_mobadmin.pub} - MOB-Admin user key
# these keys should be placed in the repo ./vagrant/ssh or in ~/.ssh folder on your host
#

Vagrant.configure(2) do |config|

  config.vm.box = "debian/jessie64"

  config.vm.define "ansnode", primary: true do |ansnode|
    ansnode.vm.network "private_network", ip: "192.168.56.101"
    ansnode.vm.provider "virtualbox" do |vb|
      vb.name = "ansnode"
      vb.memory = "1024"
    end
    ansnode.vm.synced_folder ".", "/vagrant", type: "virtualbox"

    ansnode.vm.provision "shell", path: "lib/user.sh", args: "dmitry"
    ansnode.vm.provision "shell", path: "lib/ansible.sh"

  end

  config.vm.define "mob", autostart: false do |mob|
    mob.vm.network "private_network", ip: "192.168.56.25"
    mob.vm.provider "virtualbox" do |vb|
      vb.name = "mob-server"
      vb.memory = "3096"
    end
    mob.vm.synced_folder ".", "/vagrant", type: "virtualbox"

    mob.vm.provision "shell", path: "lib/user.sh", args: "minecraft"

  end  

  config.vm.define "mob-stage", autostart: false do |stage|
    stage.vm.network "private_network", :adapter=>2, ip: "192.168.56.77"
    stage.vm.network "public_network", :adapter=>3, ip: "192.168.100.100", bridge: "Intel(R) Ethernet Connection I217-V"
    stage.vm.provider "virtualbox" do |vb|
      vb.name = "mob-stage"
      vb.memory = "4096"
    end
    stage.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    stage.vm.provision "shell", path: "lib/user.sh", args: "minecraft"
  end

  config.vm.define "desktop", autostart: false do |desktop|
    desktop.vm.provision "shell", path: "lib/user.sh", args: "dmitry"
    desktop.vm.provision "shell", path: "lib/provision-desktop.sh"

    desktop.vm.network "private_network", ip: "192.168.56.99"

    desktop.vm.provider "virtualbox" do |vb|
      vb.name = "desktop"
      vb.customize ["modifyvm", :id, "--cpus", "2", "--memory", "4096", "--accelerate3d", "on", "--accelerate2dvideo", "on", "--vram", "256"]
      vb.gui = true
    end
    desktop.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end

  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa_mobadmin.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL

  end

end
