---

# - name: Installing common applications by APT
#   apt: pkg={{ item }} state=present
#   with_items:
#     - "{{ packages }}"

- name: Set bash config
  template: src=.bashrc.j2 dest=/home/{{user}}/.bashrc

- name: Set root bash config
  template: src=.bashrc.j2 dest=/root/.bashrc

- name: Add ssh key for authentication
  authorized_key: key="{{ item }}" user="{{ user }}"
  with_items:
    - "{{ ansible_ssh_key }}"

- name: Include sshd configuration
  include_tasks: sshd.yml

- name: Include firewall configuration
  include_tasks: firewall.yml
