---
# Install docker hub

- name: Get current Debian release name
  shell: lsb_release -cs
  register: debian_release

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add apt repository for Docker CE (Debian 9+)
  apt_repository: repo="{{ item }}" state=present
  with_items:
    - "deb [arch=amd64] https://download.docker.com/linux/debian {{ debian_release.stdout }} stable"
  when: debian_release.stdout

- name: Ensure APT+https, CA certificates are installed.
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    - lxc
    - docker-ce

- name: Install Pip
  easy_install: name=pip state=latest

- name: Install Docker-PY to support Ansible
  pip: name=docker-py version=1.10.6 state=forcereinstall
