version: '3'

services:
  registry:
    image: registry:2
    ports:
    - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data
    networks:
      - mob

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: 172.18.0.1  # Make sure that this IP is host IP in your Docker network
      PMA_USER: root
      PMA_PORT: 3306
      PMA_PASSWORD: 111   # Do not forget to grant access - GRANT ALL PRIVILEGES ON *.* TO 'root'@'172.19.0.%' IDENTIFIED BY '111'; FLUSH PRIVILEGES;
    container_name: phpmyadmin
    networks:
      - mob

  dropbox:
    image: dropbox
    restart: always
    environment:
      DBOX_UID: 1000
      DBOX_GID: 1000
    volumes:
      - /home/minecraft/Dropbox:/dbox/Dropbox
      - /home/minecraft/.dropbox:/dbox/.dropbox
    network_mode: host

  minidlna:
    image: vladgh/minidlna
    restart: always
    environment:
      MINIDLNA_MEDIA_DIR_1: "V,/media/films"
      MINIDLNA_MEDIA_DIR_2: "V,/media/multics"
      MINIDLNA_MEDIA_DIR_3: "V,/media/serials"
      MINIDLNA_FRIENDLY_NAME: "HomeServer"
    volumes:
      - "/mnt/storage/Films:/media/films:ro"
      - "/mnt/storage/Multics:/media/multics:ro"
      - "/mnt/storage/Serials:/media/serials:ro"
    container_name: minidlna
    network_mode: host

  7dtd:
    image: zobees/steamcmd
    #tty: true
    #stdin_open: true
    network_mode: host
    command: "steamcmd-wrapper ./7DaysToDieServer.x86_64 -logfile /dev/stdout -configfile=serverconfig.xml -quit -batchmode -nographics -dedicated"
    environment:
      STEAMCMD_APP_ID: "294420"
      STEAMCMD_SKIP: "true"
      USER_UID: "1000"
      USER_GID: "1000"
    ports:
      - "26900:26900"
      - "26900-26902:26900-26902/udp"
      - "8081:8081"
    volumes:
      - "~/.steam/7dtd/data:/data"
      - "~/.steam/7dtd/saves:/home/steam/.local/share/7DaysToDie/Saves"

  starbound:
    image: starbound
    environment:
      USER_UID: "1000"
      USER_GID: "1000"
    ports:
      - "21025-21026:21025-21026"
    volumes:
      - "~/.gog/Starbound:/starbound"
    networks:
      - mob

networks:
  mob:
