---

- name: Update secrets in plugin config files
  become: yes
  become_user: "{{ minecraft_user }}"
  become_method: sudo
  lineinfile:
    path: "{{ server_folder }}/{{ item.path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - path: "bungeecord/plugins/BungeeChat/config.conf"
      regexp: '^\s*password='
      line: '  password="{{ minecraft_db_password }}"'
    
    - path: "bungeecord/plugins/LuckPerms/config.yml"
      regexp: '^  password:'
      line: "  password: '{{ minecraft_db_password }}'"
    
    - path: "bungeecord/plugins/SkinsRestorer/config.yml"
      regexp: '^\s*password:'
      line: "    password: '{{ minecraft_db_password }}'"
    
    - path: "creative/plugins/LogBlock/config.yml"
      regexp: '^\s*password:'
      line: '  password: {{ minecraft_db_password }}'
    
    - path: "creative/plugins/LuckPerms/config.yml"
      regexp: '^  password:'
      line: "  password: '{{ minecraft_db_password }}'"
    
    - path: "creative/plugins/PlotSquared/config/storage.yml"
      regexp: '^\s*password:'
      line: '  password: "{{ minecraft_db_password }}"'
    
    - path: "creative/plugins/DiscordSRV/config.yml"
      regexp: '^BotToken:'
      line: 'BotToken: "{{ discord_bot_token }}"'
    
    - path: "lobby/plugins/AuthMe/config.yml"
      regexp: '^\s*mySQLPassword:'
      line: '    mySQLPassword: {{ minecraft_db_password }}'
    
    - path: "lobby/plugins/DiscordSRV/config.yml"
      regexp: '^BotToken:'
      line: 'BotToken: "{{ discord_bot_token }}"'
    
    - path: "lobby/plugins/LuckPerms/config.yml"
      regexp: '^  password:'
      line: "  password: '{{ minecraft_db_password }}'"
    
    - path: "survival/plugins/EssentialsGeoIP/config.yml"
      regexp: '^\s*license-key:'
      line: '  license-key: "{{ geoip_api_key }}"'
    
    - path: "survival/plugins/LogBlock/config.yml"
      regexp: '^\s*password:'
      line: '  password: {{ minecraft_db_password }}'
    
    - path: "survival/plugins/LuckPerms/config.yml"
      regexp: '^  password:'
      line: "  password: '{{ minecraft_db_password }}'"
    
    - path: "survival/plugins/WorldGuard/config.yml"
      regexp: '^\s*password:'
      line: '        password: {{ minecraft_db_password }}'
    
    - path: "survival/plugins/DiscordSRV/config.yml"
      regexp: '^BotToken:'
      line: 'BotToken: "{{ discord_bot_token }}"'
    
    - path: "vanilla/plugins/DiscordSRV/config.yml"
      regexp: '^BotToken:'
      line: 'BotToken: "{{ discord_bot_token }}"'
    
    - path: "vanilla/plugins/LogBlock/config.yml"
      regexp: '^\s*password:'
      line: '  password: {{ minecraft_db_password }}'
    
    - path: "vanilla/plugins/LuckPerms/config.yml"
      regexp: '^  password:'
      line: "  password: '{{ minecraft_db_password }}'"

    - path: "survival/plugins/Jobs/generalConfig.yml"
      regexp: '^\s*password:'
      line: '  password: {{ minecraft_db_password }}'
