---

- name: Update mysql passwords in live config
  replace: dest="{{server_folder }}/{{ item.name }}" regexp="{{ item.name }}" replace="\1 {{ password }}"
  with_items:
    - dest: "bungeecord/plugins/SkinsRestorer/config.yml"
      regexp: "^  Password: 111\s*$"

    - dest: "lobby/plugins/AuthMe/config.yml"
      regexp: "mySQLPassword: '111'"

    - dest: "survival/plugins/LogBlock/config.yml"
      regexp: "^password: 111$"

    - dest: "survival/plugins/PermissionsEx/config.yml"
      regexp: "^password: 111\s*$"

    - dest: "survival/plugins/WorldGuard/config.yml"
      regexp: "^password: 111\s*$"

    - dest: "survival/plugins/WorldGuard/config.yml"
      regexp: "^pass: '111'\s*$"

#- name: Setup alternate SSH port
#  lineinfile:
#    dest: "bungeecord/plugins/SkinsRestorer/config.yml"
#    regexp: "^password: 111"
#    line: "password: 111"
