---

- include: packages.yml

- include: maintenance.yml
  when: mode == "update"

- include: repo.yml

- include: configure.yml

# - include: worlds.yml
#   when: mode == "setup" or mode == "reset"

# - include: database.yml
#   when: mode == "setup"

# - include: services.yml
#   when: mode == "setup"

