---

- name: Create a project folder if not exists
  file:
    path: "{{ server_folder }}"
    state: directory
    mode: '0755'
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"

- name: Checkout servers repo and update to the latest version
  become: yes
  become_user: "{{ minecraft_user }}"
  become_method: sudo
  git:
    repo: "{{ server_repo }}"
    dest: "{{ server_folder }}"
    version: "{{ server_release }}"
    force: yes
    accept_hostkey: yes

