---

- name: Create Minecraft Backups folder
  file:
    path: "{{ backup_folder }}"
    state: directory
    mode: '0755'
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"

- name: Download and unpack server sources from S3
  block:
    - name: Create server source folders
      file:
        path: "{{ server_folder }}/{{ item.name }}/{{ item.world }}/"
        state: directory
        mode: 0755
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
      loop:
        - { name: "lobby", world: "lobby" }
        - { name: "survival", world: "survival" }
        - { name: "survival", world: "survival_nether" }
        - { name: "survival", world: "survival_the_end" }
        - { name: "vanilla", world: "vanilla" }

    - name: Download server sources from S3
      become: yes
      become_user: "{{ minecraft_user }}"
      aws_s3:
        bucket: "{{ server_src.bucket }}"
        object: "{{ server_src.path }}/{{ item.archive }}"
        dest: "{{ server_folder }}/{{ item.name }}/{{ item.archive }}"
        mode: get
      loop:
        - { name: "lobby", archive: "lobby.tar.gz" }
        - { name: "survival", archive: "survival.tar.gz" }
        - { name: "vanilla", archive: "vanilla.tar.gz" }
      register: s3_downloads

    - name: Unpack server sources
      become: yes
      become_user: "{{ minecraft_user }}"
      unarchive:
        src: "{{ server_folder }}/{{ item.name }}/{{ item.archive }}"
        dest: "{{ server_folder }}/{{ item.name }}/"
        remote_src: yes
        force: yes
      loop:
        - { name: "lobby", archive: "lobby.tar.gz" }
        - { name: "survival", archive: "survival.tar.gz" }
        - { name: "vanilla", archive: "vanilla.tar.gz" }

