---

# Minecraft database configuration
minecraft_db_name: mob_server
minecraft_db_user: minecraft

# Character set configuration
mariadb_character_set: utf8mb4
mariadb_collation: utf8mb4_unicode_ci

# Fine tuning parameters
mariadb_max_connections: 200
mariadb_connect_timeout: 5
mariadb_wait_timeout: 900
mariadb_max_allowed_packet: 128M
mariadb_thread_cache_size: 128
mariadb_sort_buffer_size: 4M
mariadb_bulk_insert_buffer_size: 16M
mariadb_tmp_table_size: 32M
mariadb_max_heap_table_size: 32M
mariadb_skip_name_resolve: true

# Authentication
mysql_disable_unix_socket_auth: true

# Allowed networks for MariaDB access
allowed_networks:
  - localhost
  - 127.0.0.1
  - ::1
  - 10.10.10.0/24
  - 192.168.56.0/24
