# Set up and configure Apache2 to server
#
# ansible-playbook -i ./inventory/dev apache2.yml --extra-vars "env=mobsite-dev user=vagrant" -vv -c paramiko

- hosts: "{{env}}"
  user: "{{user}}"
  become: yes
  become_method: sudo
  gather_facts: true
  max_fail_percentage: 0

  roles:
    - apache2
