# setup common system applications
# ansible-playbook -i ./inventory/dev common.yml --extra-vars "env=mobserver user=minecraft env=prod" -vv

- hosts: "{{ env }}"
  user: "{{ user }}"
  become: yes
  become_method: sudo
  gather_facts: true
  roles:
    - common
