# MOB server provisioning
#
# ansible-playbook -i ./inventory/live mob-server-provision.yml --extra-vars "env=mob-server password=Secret123 env_type=live" -vv

- hosts: "{{env}}"
  user: vagrant
  become: yes
  become_method: sudo
  gather_facts: true
  roles:
    - mob-server-provision

  vars_files:
    - host_vars/{{env}}