# MOB site deployment
#
# ansible-playbook -i ./inventory/stage mob-site-deploy.yml --extra-vars "env=mob-site-stage password=Secret123 env_type=stage" -vv

- hosts: "{{env}}"
  user: vagrant
  become: yes
  become_method: sudo
  gather_facts: true
  max_fail_percentage: 0

  roles:
    - mob-site-deploy
