# MOB server provisioning
#
# ansible-playbook -i ./inventory/dev mob-server-provision.yml  -e "env=mobserver user=minecraft" -e "@local.vars.yml" -v
# ansible-playbook -i ./inventory/live mob-server-provision.yml -e "env=mobserver-vps user=minecraft" -e "@local.vars.yml" -v

- hosts: "{{env}}"
  user: "{{user}}"
  become: yes
  become_method: sudo
  gather_facts: true
  roles:
    - mob-server-provision
