# Setup MySQL server
# ansible-playbook -i ./inventory/dev mysql.yml --extra-vars "env=desktop user=vagrant mysql_engine=MyISAM mysql_rootpass=Secret123" -vv -c paramiko

- hosts: "{{env}}"
  user: "{{user}}"
  become: yes
  become_method: sudo
  gather_facts: true
  roles:
    - mysql
