# Setup nodejs
# ansible-playbook -i ./inventory/dev nodejs.yml --extra-vars "env=mobsite-dev user=dmitry" -vv

- hosts: "{{env}}"
  user: "{{user}}"
  become: yes
  become_method: sudo
  gather_facts: true
  roles:
    - nodejs

  vars_files:
    - host_vars/{{env}}
